# =========================================================================
# Clash 手机版专用配置文件 (兼容性优化版)
# =========================================================================

# -------------------------------------------------------------------------
# 基本配置 (Basic Configuration)
# -------------------------------------------------------------------------
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
unified-delay: true

# DNS 配置
dns:
  enable: true
  enhanced-mode: redir-host
  # listen: 0.0.0.0:5353 # 根据需要决定是否开启
  nameservers:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
  
  fallback:
    - "tls://dns.google:853"
    - "https://dns.cloudflare.com/dns-query"
  
  # fallback-filter 配置已修改
  # 移除 geosite: true 和 geoip: true，以避免兼容性问题
  # 保持 ipcidr，因为它通常是通用的
  fallback-filter:
    ipcidr:
      - "0.0.0.0/8"
      - "10.0.0.0/8"
      - "100.64.0.0/10"
      - "127.0.0.0/8"
      - "169.254.0.0/16"
      - "172.16.0.0/12"
      - "192.0.0.0/24"
      - "192.0.2.0/24"
      - "192.88.99.0/24"
      - "192.168.0.0/16"
      - "198.18.0.0/15"
      - "198.51.100.0/24"
      - "203.0.113.0/24"
      - "224.0.0.0/3"
      - "::1/128"
      - "fc00::/7"
      - "fe80::/10"

# -------------------------------------------------------------------------
# 代理节点定义 (Proxies)
# -------------------------------------------------------------------------
proxies:
  - name: "wyl bwg (VLESS)"
    type: vless
    server: imwyl.cc
    port: 444
    uuid: 3a760a9b-c52d-4d24-91c1-f9daea8fefcb
    tls: true
    network: tcp
    flow: xtls-rprx-vision
    servername: imwyl.cc
    alpn:
      - h2
      - http/1.1
    client-fingerprint: firefox
    udp: true

  - name: "hua racknerd (Hysteria2)"
    type: hysteria2
    server: 209.54.107.202
    port: 47453
    password: "18cb90e9"
    tls: true
    skip-cert-verify: true
    sni: www.bing.com
    udp: true

# -------------------------------------------------------------------------
# 代理组定义 (Proxy Groups)
# -------------------------------------------------------------------------
proxy-groups:
  - name: "Google AI Proxy"
    type: select
    proxies:
      - "wyl bwg (VLESS)"
      - "hua racknerd (Hysteria2)"
      - "DIRECT"

  - name: "General Proxy (PAC)"
    type: select
    proxies:
      - "hua racknerd (Hysteria2)"
      - "DIRECT"

# -------------------------------------------------------------------------
# 路由规则 (Rules)
# -------------------------------------------------------------------------
rules:
  - DOMAIN-SUFFIX,gemini.google.com,Google AI Proxy
  - DOMAIN-SUFFIX,bard.google.com,Google AI Proxy
  - DOMAIN-SUFFIX,ai.google.com,Google AI Proxy
  - DOMAIN-SUFFIX,generativelanguage.googleapis.com,Google AI Proxy
  - DOMAIN-SUFFIX,accounts.google.com,Google AI Proxy
  - DOMAIN-SUFFIX,clientservices.googleapis.com,Google AI Proxy
  - DOMAIN-SUFFIX,www.google.com,Google AI Proxy
  - DOMAIN-SUFFIX,google.com,Google AI Proxy
  - DOMAIN-SUFFIX,gstatic.com,Google AI Proxy
  - DOMAIN-SUFFIX,fonts.gstatic.com,Google AI Proxy
  - DOMAIN-SUFFIX,googleapis.com,Google AI Proxy

  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT,no-resolve

  - MATCH,General Proxy (PAC)
